/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import java.awt.TextField;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Asus
 */
public class UsersPanel extends javax.swing.JFrame {
    static void setModel(DefaultTableModel defaultTableModel) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    DefaultTableModel defaultTableModel=new DefaultTableModel();
    Object[] coloms={"BarkodNumarasi","KitapAdi","KitapYazari","KitapBaskıYılı","KitapSayfaSayisi","Dil","KitapYayınevi","Durum"};
    Object[] line=new Object[8];
    /**
     * Creates new form UsersPanel
     */
    public UsersPanel() {
        initComponents();
        showTable("select * from kitaplar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Exit_users_button = new javax.swing.JButton();
        TxtKitapAdi = new javax.swing.JTextField();
        TxtKitapYazari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TxtKitapAra = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        yenidenara = new javax.swing.JButton();
        TxtYazarAra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        users_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kullanıcı Paneli");
        setLocation(new java.awt.Point(350, 150));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        Exit_users_button.setBackground(new java.awt.Color(102, 102, 102));
        Exit_users_button.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        Exit_users_button.setForeground(new java.awt.Color(255, 255, 255));
        Exit_users_button.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\Software\\icons for java\\red-cross-icon.png")); // NOI18N
        Exit_users_button.setText("Çıkış");
        Exit_users_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit_users_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_users_buttonActionPerformed(evt);
            }
        });

        TxtKitapAdi.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                TxtKitapAdiİnputMethodTextChanged(evt);
            }
        });
        TxtKitapAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKitapAdiActionPerformed(evt);
            }
        });

        TxtKitapYazari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKitapYazariActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kitap Adı: ");

        TxtKitapAra.setBackground(new java.awt.Color(102, 102, 102));
        TxtKitapAra.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        TxtKitapAra.setForeground(new java.awt.Color(255, 255, 255));
        TxtKitapAra.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\Software\\icons for java\\Google-Play-Books-icon (1).png")); // NOI18N
        TxtKitapAra.setText("Kitap Ara");
        TxtKitapAra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtKitapAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKitapAraActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Yazar:");

        yenidenara.setBackground(new java.awt.Color(102, 102, 102));
        yenidenara.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        yenidenara.setForeground(new java.awt.Color(255, 255, 255));
        yenidenara.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\Software\\icons for java\\blue-search-icon.png")); // NOI18N
        yenidenara.setText("Yeniden Ara");
        yenidenara.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yenidenara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yenidenaraActionPerformed(evt);
            }
        });

        TxtYazarAra.setBackground(new java.awt.Color(102, 102, 102));
        TxtYazarAra.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        TxtYazarAra.setForeground(new java.awt.Color(255, 255, 255));
        TxtYazarAra.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\Software\\icons for java\\user-search-icon.png")); // NOI18N
        TxtYazarAra.setText("Yazar Ara");
        TxtYazarAra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtYazarAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtYazarAraActionPerformed(evt);
            }
        });

        users_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(users_table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtKitapYazari)
                            .addComponent(TxtKitapAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtYazarAra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtKitapAra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(yenidenara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Exit_users_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 81, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtKitapAra, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yenidenara, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtKitapAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtKitapYazari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtYazarAra, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Exit_users_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Exit_users_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_users_buttonActionPerformed
        dispose();
    }//GEN-LAST:event_Exit_users_buttonActionPerformed

    private void TxtKitapAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKitapAraActionPerformed
        String KitapAdi=TxtKitapAdi.getText();
        String aramasorgu = "Select * FROM kitaplar WHERE KitapAdi= '" + KitapAdi + "'";
        System.out.println(aramasorgu);
        defaultTableModel.setColumnCount(0);
        defaultTableModel.setRowCount(0);
        showTable(aramasorgu);
    }//GEN-LAST:event_TxtKitapAraActionPerformed

    private void TxtKitapAdiİnputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_TxtKitapAdiİnputMethodTextChanged
        
        String KitapAdi=TxtKitapAdi.getText();
        String aramasorgu = "Select * FROM kitaplar WHERE KitapAdi= '" + KitapAdi + "'";
        System.out.println(aramasorgu);
        defaultTableModel.setColumnCount(0);
        defaultTableModel.setRowCount(0);
        showTable(aramasorgu);
        
    }//GEN-LAST:event_TxtKitapAdiİnputMethodTextChanged

    private void TxtKitapAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKitapAdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtKitapAdiActionPerformed

    private void yenidenaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yenidenaraActionPerformed
        TxtKitapAdi.setText("");
        TxtKitapYazari.setText("");
        defaultTableModel.setColumnCount(0);
        defaultTableModel.setRowCount(0);
    }//GEN-LAST:event_yenidenaraActionPerformed

    private void TxtKitapYazariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKitapYazariActionPerformed
        
    }//GEN-LAST:event_TxtKitapYazariActionPerformed

    private void TxtYazarAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtYazarAraActionPerformed
        String KitapYazari=TxtKitapYazari.getText();
        String aramasorgu = "Select * FROM kitaplar WHERE KitapYazari= '" + KitapYazari + "'";
        System.out.println(aramasorgu);
        defaultTableModel.setColumnCount(0);
        defaultTableModel.setRowCount(0);
        showTable(aramasorgu);
    }//GEN-LAST:event_TxtYazarAraActionPerformed
    

    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersPanel().setVisible(true);
            }
        });
    }
    
    
    private void showTable(String sqlRequest){
        
        ResultSet resultSet=DataBase.DataBaseConnection.list(sqlRequest);
        defaultTableModel.setColumnIdentifiers(coloms);
        try {
            while(resultSet.next()){
                line[0]=resultSet.getString("BarkodNumarasi");
                line[1]=resultSet.getString("KitapAdi");
                line[2]=resultSet.getString("KitapYazari");
                line[3]=resultSet.getString("KitapBaskıYılı");
                line[4]=resultSet.getString("KitapSayfaSayisi");
                line[5]=resultSet.getString("Dil");
                line[6]=resultSet.getString("KitapYayınevi");
                line[7]=resultSet.getString("Durum");
                defaultTableModel.addRow(line);
            }
            users_table.setModel(defaultTableModel);
        } catch (Exception e) {
            e.printStackTrace();

            
    }
        
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit_users_button;
    private javax.swing.JTextField TxtKitapAdi;
    private javax.swing.JButton TxtKitapAra;
    private javax.swing.JTextField TxtKitapYazari;
    private javax.swing.JButton TxtYazarAra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable users_table;
    private javax.swing.JButton yenidenara;
    // End of variables declaration//GEN-END:variables
}

