/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Frame.Adminİslemleri;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class ÖdüncVerme extends javax.swing.JFrame {
     static void setModel(DefaultTableModel defaultTableModel) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static int getSelectedRow() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    DefaultTableModel defaultTableModel=new DefaultTableModel();
    Object[] coloms={"UyeTcKimlik","UyeKAdi","OduncVerenKAdi","VerilenKitapAdı","KitapBarkodNo","EmanetVermeTarihi","EmanetBitimTarihi","TeslimEdildiMi"};
    Object[] line=new Object[8];

    /**
     * Creates new form ÖdüncVerme
     */
    public ÖdüncVerme() {
        initComponents();
//      eklemepanel.setVisible(false);
      
      
      showTable("select * from TblOduncIslemi");
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        eklemepanel = new javax.swing.JPanel();
        UyeKAdi = new javax.swing.JTextField();
        VerilenKitapAdı = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        KitapBarkodNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        EmanetVermeTarihi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EmanetBitimTarihi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TeslimEdildiMi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        OduncVerenKAdi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        UyeTcKimlik = new javax.swing.JTextField();
        ÖdünçVermeButton = new javax.swing.JButton();
        ListeleButonu = new javax.swing.JButton();
        panelarama = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        KullaniciAdi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        users_table = new javax.swing.JTable();
        Ara = new javax.swing.JButton();
        geridonusbutonu = new javax.swing.JButton();
        Btntemizle = new javax.swing.JButton();
        ödüncdencıkısbutonu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ödünç Verme ");
        setBackground(new java.awt.Color(51, 51, 51));
        setLocation(new java.awt.Point(15, 75));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oduncpanel(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/ywnnii.png"))); // NOI18N

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 3, 11)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/green-ok-icon.png"))); // NOI18N
        jLabel12.setText("ÖDÜNÇ VERME İŞLEMLERİ");

        eklemepanel.setBackground(new java.awt.Color(0, 102, 102));
        eklemepanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Üye Tc Kimlik Numarası:");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Üye Kullanıcı Adı:");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ödünç Veren Kişi: ");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ödünç Verilen Kitap:");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kitap Barkod Numarası:");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Emanet Verme Tarihi:");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Emanet İade Tarihi:");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Teslim Durumu:");

        ÖdünçVermeButton.setBackground(new java.awt.Color(0, 0, 0));
        ÖdünçVermeButton.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        ÖdünçVermeButton.setForeground(new java.awt.Color(255, 255, 255));
        ÖdünçVermeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/kaydet.png"))); // NOI18N
        ÖdünçVermeButton.setText("Ödünç Kayıt");
        ÖdünçVermeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ÖdünçVermeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ÖdünçVermeButtonActionPerformed(evt);
            }
        });

        ListeleButonu.setBackground(new java.awt.Color(0, 0, 0));
        ListeleButonu.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        ListeleButonu.setForeground(new java.awt.Color(255, 255, 255));
        ListeleButonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/listele.png"))); // NOI18N
        ListeleButonu.setText("Bütün Kayıtları Listele");
        ListeleButonu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListeleButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeleButonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eklemepanelLayout = new javax.swing.GroupLayout(eklemepanel);
        eklemepanel.setLayout(eklemepanelLayout);
        eklemepanelLayout.setHorizontalGroup(
            eklemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(eklemepanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(eklemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(eklemepanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TeslimEdildiMi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(eklemepanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EmanetVermeTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, eklemepanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EmanetBitimTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(eklemepanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(eklemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(eklemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eklemepanelLayout.createSequentialGroup()
                        .addComponent(KitapBarkodNo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(eklemepanelLayout.createSequentialGroup()
                        .addGroup(eklemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(eklemepanelLayout.createSequentialGroup()
                                .addGroup(eklemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(OduncVerenKAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UyeKAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UyeTcKimlik, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(ÖdünçVermeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(eklemepanelLayout.createSequentialGroup()
                                .addComponent(VerilenKitapAdı, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ListeleButonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        eklemepanelLayout.setVerticalGroup(
            eklemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eklemepanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(eklemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(eklemepanelLayout.createSequentialGroup()
                        .addGroup(eklemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UyeTcKimlik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(eklemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(UyeKAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(eklemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(OduncVerenKAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(eklemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VerilenKitapAdı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(eklemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KitapBarkodNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(eklemepanelLayout.createSequentialGroup()
                        .addComponent(ÖdünçVermeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ListeleButonu, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(eklemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(EmanetVermeTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(eklemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(EmanetBitimTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(eklemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TeslimEdildiMi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        panelarama.setBackground(new java.awt.Color(0, 102, 102));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Üye Kullanıcı Adı :");
        jLabel9.setAutoscrolls(true);

        KullaniciAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KullaniciAdiActionPerformed(evt);
            }
        });

        users_table.setBackground(new java.awt.Color(0, 153, 153));
        users_table.setForeground(new java.awt.Color(102, 0, 0));
        users_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(users_table);

        Ara.setBackground(new java.awt.Color(0, 0, 0));
        Ara.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        Ara.setForeground(new java.awt.Color(255, 255, 255));
        Ara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/ara.png"))); // NOI18N
        Ara.setText("Ara");
        Ara.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelaramaLayout = new javax.swing.GroupLayout(panelarama);
        panelarama.setLayout(panelaramaLayout);
        panelaramaLayout.setHorizontalGroup(
            panelaramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelaramaLayout.createSequentialGroup()
                .addGroup(panelaramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelaramaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ara, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 347, Short.MAX_VALUE))
                    .addGroup(panelaramaLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelaramaLayout.setVerticalGroup(
            panelaramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelaramaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelaramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelaramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(KullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Ara, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        geridonusbutonu.setBackground(new java.awt.Color(0, 0, 0));
        geridonusbutonu.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        geridonusbutonu.setForeground(new java.awt.Color(255, 255, 255));
        geridonusbutonu.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\Software\\icons for java\\back-icon.png")); // NOI18N
        geridonusbutonu.setText("Önceki Menü");
        geridonusbutonu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        geridonusbutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geridonusbutonuActionPerformed(evt);
            }
        });

        Btntemizle.setBackground(new java.awt.Color(0, 0, 0));
        Btntemizle.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        Btntemizle.setForeground(new java.awt.Color(255, 255, 255));
        Btntemizle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/green-document-cross-icon.png"))); // NOI18N
        Btntemizle.setText("Temizle");
        Btntemizle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btntemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtntemizleActionPerformed(evt);
            }
        });

        ödüncdencıkısbutonu.setBackground(new java.awt.Color(0, 0, 0));
        ödüncdencıkısbutonu.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        ödüncdencıkısbutonu.setForeground(new java.awt.Color(255, 255, 255));
        ödüncdencıkısbutonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/exit.png"))); // NOI18N
        ödüncdencıkısbutonu.setText("Çıkış");
        ödüncdencıkısbutonu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ödüncdencıkısbutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ödüncdencıkısbutonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(eklemepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelarama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(geridonusbutonu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(Btntemizle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(ödüncdencıkısbutonu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addComponent(eklemepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelarama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btntemizle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ödüncdencıkısbutonu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(geridonusbutonu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ÖdünçVermeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ÖdünçVermeButtonActionPerformed
        // TODO add your handling code here:
        
        String UyeTcKimlikk, UyeKAdii,OduncVerenKAdii,VerilenKitapAdıı,KitapBarkodNoo,EmanetVermeTarihii,EmanetBitimTarihii,TeslimEdildiMii;
            UyeTcKimlikk=UyeTcKimlik.getText();
            UyeKAdii=UyeKAdi.getText();
            OduncVerenKAdii=OduncVerenKAdi.getText();
            VerilenKitapAdıı=VerilenKitapAdı.getText();
            KitapBarkodNoo=KitapBarkodNo.getText();
            EmanetVermeTarihii=EmanetVermeTarihi.getText();
            EmanetBitimTarihii=EmanetBitimTarihi.getText();
            TeslimEdildiMii=TeslimEdildiMi.getText();
      
            String insertSQL = "INSERT INTO TblOduncIslemi (UyeTcKimlik,UyeKAdi,OduncVerenKAdi,VerilenKitapAdı,KitapBarkodNo,EmanetVermeTarihi,EmanetBitimTarihi,TeslimEdildiMi )"+ "VALUES ('" + UyeTcKimlikk +"' ,'" + UyeKAdii +"' ,'"+OduncVerenKAdii+"' ,'" +VerilenKitapAdıı+ "' ,'" +KitapBarkodNoo+"' ,'" +EmanetVermeTarihii+"' ,'" +EmanetBitimTarihii+"' ,'" +TeslimEdildiMii+"')";
            DataBase.DataBaseConnection.insert(insertSQL);
            defaultTableModel.setColumnCount(0);
            defaultTableModel.setRowCount(0);
            tablogoster();
    }//GEN-LAST:event_ÖdünçVermeButtonActionPerformed

    private void AraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AraActionPerformed
        // TODO add your handling code here:
        String KullaniciAdii=KullaniciAdi.getText();
        String aramasorgu = "Select * FROM TblOduncIslemi WHERE UyeKAdi= '" + KullaniciAdii + "'";
        System.out.println(aramasorgu);
        defaultTableModel.setColumnCount(0);
        defaultTableModel.setRowCount(0);
        showTable(aramasorgu);
        
    }//GEN-LAST:event_AraActionPerformed

    private void BtntemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtntemizleActionPerformed
        // TODO add your handling code here:
        KullaniciAdi.setText("");
        UyeTcKimlik.setText("");
        UyeKAdi.setText("");
        OduncVerenKAdi.setText("");
        VerilenKitapAdı.setText("");
        KitapBarkodNo.setText("");
        EmanetVermeTarihi.setText("");
        EmanetBitimTarihi.setText("");
        TeslimEdildiMi.setText("");
        defaultTableModel.setColumnCount(0);
        defaultTableModel.setRowCount(0);
    }//GEN-LAST:event_BtntemizleActionPerformed

    private void ödüncdencıkısbutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ödüncdencıkısbutonuActionPerformed
        dispose();
    }//GEN-LAST:event_ödüncdencıkısbutonuActionPerformed

    private void ListeleButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeleButonuActionPerformed
        // TODO add your handling code here:
        tablogoster();
        
    }//GEN-LAST:event_ListeleButonuActionPerformed

            
    private void oduncpanel(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oduncpanel
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_oduncpanel

    private void geridonusbutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geridonusbutonuActionPerformed
        // TODO add your handling code here:
        Adminİslemleri  frm3 = new Adminİslemleri();
        frm3.setVisible(true); 
        dispose();
    }//GEN-LAST:event_geridonusbutonuActionPerformed

    private void KullaniciAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KullaniciAdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KullaniciAdiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ÖdüncVerme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ÖdüncVerme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ÖdüncVerme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ÖdüncVerme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ÖdüncVerme().setVisible(true);
            }
        });
    }
     private void showTable(String sqlRequest){
        
        ResultSet resultSet=DataBase.DataBaseConnection.list(sqlRequest);
        defaultTableModel.setColumnIdentifiers(coloms);
        try {
            while(resultSet.next()){
                line[0]=resultSet.getString("UyeTcKimlik");
                line[1]=resultSet.getString("UyeKAdi");
                line[2]=resultSet.getString("OduncVerenKAdi");
                line[3]=resultSet.getString("VerilenKitapAdı");
                line[4]=resultSet.getString("KitapBarkodNo");
                line[5]=resultSet.getString("EmanetVermeTarihi");
                line[6]=resultSet.getString("EmanetBitimTarihi");
                line[7]=resultSet.getString("TeslimEdildiMi");
                defaultTableModel.addRow(line);
            }
            users_table.setModel(defaultTableModel);
        } catch (Exception e) {
            e.printStackTrace();

            
    }
        
            
    }
     
      private void tablogoster(){
        
         String sqlRequest = "select * from TblOduncIslemi ";
        ResultSet resultSet=DataBase.DataBaseConnection.list(sqlRequest);
        defaultTableModel.setColumnIdentifiers(coloms);
        try {
            while(resultSet.next()){
                line[0]=resultSet.getString("UyeTcKimlik");
                line[1]=resultSet.getString("UyeKAdi");
                line[2]=resultSet.getString("OduncVerenKAdi");
                line[3]=resultSet.getString("VerilenKitapAdı");
                line[4]=resultSet.getString("KitapBarkodNo");
                line[5]=resultSet.getString("EmanetVermeTarihi");
                line[6]=resultSet.getString("EmanetBitimTarihi");
                line[7]=resultSet.getString("TeslimEdildiMi");
                defaultTableModel.addRow(line);
            }
            users_table.setModel(defaultTableModel);
        } catch (Exception e) {
            e.printStackTrace();

            
    }
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ara;
    private javax.swing.JButton Btntemizle;
    private javax.swing.JTextField EmanetBitimTarihi;
    private javax.swing.JTextField EmanetVermeTarihi;
    private javax.swing.JTextField KitapBarkodNo;
    private javax.swing.JTextField KullaniciAdi;
    private javax.swing.JButton ListeleButonu;
    private javax.swing.JTextField OduncVerenKAdi;
    private javax.swing.JTextField TeslimEdildiMi;
    private javax.swing.JTextField UyeKAdi;
    private javax.swing.JTextField UyeTcKimlik;
    private javax.swing.JTextField VerilenKitapAdı;
    private javax.swing.JPanel eklemepanel;
    private javax.swing.JButton geridonusbutonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelarama;
    private javax.swing.JTable users_table;
    private javax.swing.JButton ÖdünçVermeButton;
    private javax.swing.JButton ödüncdencıkısbutonu;
    // End of variables declaration//GEN-END:variables
}
